doddle/compare/urls.py
from django.conf.urls import patterns, url
from compare import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

doddle/doddle/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.backends.default.views import RegistrationView
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('home.urls')),
    url(r'^about/', include('django.contrib.flatpages.urls')),
    url(r'^faq/', include('django.contrib.flatpages.urls')),
    url(r'^compare/', include('compare.urls')),
    url(r'^agents/', include('agents.urls')),
    url(r'^properties/', include('properties.urls'), name='properties'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^my-profile/', include('profiles.urls')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/password/change/$', 'django.contrib.auth.views.password_change'),
    url(r'^accounts/password/password-changed/$', 'django.contrib.auth.views.password_change_done'),
    url(r'^accounts/password/reset/$', 'django.contrib.auth.views.password_reset'),
    url(r'^accounts/password/password-reset/$', 'django.contrib.auth.views.password_reset_complete'),
    url(r'^accounts/register/$', RegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/register/complete/$', TemplateView.as_view(template_name='registration/registration_complete.html'), name='registration_complete'),
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'^unimoveadmin/', include(admin.site.urls)),
)

doddle/home/urls.py
from django.conf.urls import patterns, url
from home import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

doddle/compare/models.py
from django.db import models

# Create your models here.

doddle/properties/models.py
from django.db import models
from agents.models import Agent
from profiles.models import UserProfile
import os


def get_upload_path(instance, filename):
    return os.path.join("static/properties/images/%d/" % instance.property_id, filename)


#Set approved constants
YES = 'y'
NO = 'n'

#Set the array to be displayed in dropdown
YES_NO = (
    (YES, 'Yes'),
    (NO, 'No')
)


class Property(models.Model):
    line_one = models.CharField(max_length=100)
    line_two = models.CharField(max_length=100)
    city = models.CharField(max_length=20)
    postcode = models.CharField(max_length=8)

    HOUSE = 'house'
    FLAT = 'flat/apartment'

    TYPE = (
        (HOUSE, 'House'),
        (FLAT, 'Flat/Apartment')
    )

    type = models.CharField(max_length=20, choices=TYPE)

    agent = models.ForeignKey(Agent)
    description = models.TextField(max_length=10000)
    price = models.IntegerField(max_length=20)

    approved = models.CharField(max_length=1, choices=YES_NO, default=NO)
    featured = models.CharField(max_length=1, choices=YES_NO, default=NO)
    date_available = models.DateField()
    no_of_bedrooms = models.CharField(max_length=2, default=1)
    no_of_bathrooms = models.CharField(max_length=1, default=1)
    bills_included = models.CharField(max_length=1, choices=YES_NO, default=NO)
    is_furnished = models.CharField(max_length=1, choices=YES_NO, default=NO)

    def __str__(self):
        return self.line_one

    def is_approved(self):
        return self.approved
    is_approved.admin_order_field = 'approved'
    is_approved.boolean = True
    is_approved.short_description = 'Approved?'


class PropertyImage(models.Model):
    property = models.ForeignKey(Property)
    image = models.ImageField(upload_to=get_upload_path)
    is_main = models.CharField(max_length=1, choices=YES_NO)


class Review(models.Model):
    property = models.ForeignKey(Property)

    ONE = 1
    TWO = 2
    THREE = 3
    FOUR = 4
    FIVE = 5

    STAR_RATING = (
        (ONE, '1'),
        (TWO, '2'),
        (THREE, '3'),
        (FOUR, '4'),
        (FIVE, '5')
    )

    star_rating = models.IntegerField(max_length=1, choices=STAR_RATING, default=ONE)
    comment = models.TextField(max_length=1000)

    approved = models.CharField(max_length=1, choices=YES_NO, default=NO)

    def __str__(self):
        return self.property.line_one


class SavedProperty(models.Model):
    user = models.ForeignKey(UserProfile)
    property = models.ForeignKey(Property)

doddle/compare/views.py
from django.shortcuts import render
from django.http import HttpResponse
from properties.models import Property


def index(request):
    property = Property.objects.filter()
    return render(request, 'compare/index.html', {
        'property': property
    })

doddle/compare/templates/compare/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'properties/css/style.css' %}" />
    <div class="content">
        <div class="container">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Property</th>
                    <th>Price</th>
                    <th>Bedrooms</th>
                    <th>Bathrooms</th>
                    <th>Bills Included?</th>
                    <th>Date Available</th>
                </tr>
                </thead>
                <tbody>
                {% for property in property %}
                    {% for saved in property.savedproperty_set.all %}
                        <tr>
                            <td>
                                {% for image in property.propertyimage_set.all|dictsortreversed:"is_main"|slice:":1" %}
                                    <a href="{% url 'view' property.id %}"><img class="index-image" src="/{{ image.image.url }}"></a><br />
                                {% endfor %}
                                {{ property.line_one }}
                                <p><a href="#_" property-id="{{ property.id }}" class="danger-small">Remove</a></p>
                            </td>
                            <td>£{{ property.price }}</td>
                            <td>{{ property.no_of_bedrooms }}</td>
                            <td>{{ property.no_of_bathrooms }}</td>
                            {% if property.bills_included == 'y' %}
                                <td>Yes</td>
                            {% else %}
                                <td>No</td>
                            {% endif %}
                            <td>{{ property.date_available }}</td>
                            <td><a href="{% url 'enquire' property.id %}" class="enquire-btn btn btn-large">Request details</a></td>
                        </tr>
                    {% endfor %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $(".danger-small").on("click", function () {
                propertyId = $(this).attr('property-id');
                userId = {{ request.user.id }};
                $.ajax ({
                    url:"/properties/remove-saved-property/",
                    data: {propertyId : propertyId, userId : userId},
                    dataType: "json",
                    type: "POST",
                    success: function(data){
                        response(data);
                    }
                });
                $(this).closest("tr").fadeOut("slow");
            });
        });
    </script>
{% endblock %}